apiVersion: v1
kind: ConfigMap
metadata:
  name: secret-duplicator-cert-gen-entrypoint
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "secret-duplicator.labels" . | nindent 4 }}
data:
  entrypoint.sh: | {{ .Files.Get "scripts/create-signed-cert.sh" | nindent 4 }}
