apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: "{{ .Release.Name }}-cert-gen-cron-job"
  labels:
    {{- include "secret-duplicator.labels" . | nindent 4 }}
spec:
  schedule: '* * * * 0'
  jobTemplate:
    metadata:
      name: "{{ .Release.Name }}"
      labels:
        {{- include "secret-duplicator.labels" . | nindent 8 }}
    spec:
      ttlSecondsAfterFinished: 30
      template:
        spec:
          serviceAccountName: secret-duplicator-cert-gen
          restartPolicy: Never
          containers:
            - name: pre-install-job
              image: "{{ .Values.certificateGeneratorImage.registry }}/{{ .Values.certificateGeneratorImage.repository }}:{{ .Values.certificateGeneratorImage.tag | default .Chart.AppVersion }}"
              command: ["/entrypoint/entrypoint.sh"]
              args:
                - --service
                - "{{ include "secret-duplicator.serviceName" . }}"
                - --namespace
                - "{{ .Release.Namespace }}"
                - --secret
                - "{{ include "secret-duplicator.certificateSecretName" . }}"
              volumeMounts:
                - mountPath: "/entrypoint"
                  name: entrypoint
          volumes:
            - name: entrypoint
              configMap:
                name: secret-duplicator-cert-gen-entrypoint
                items:
                  - key: entrypoint.sh
                    path: entrypoint.sh
                    mode: 0755
