apiVersion: v1
kind: ServiceAccount
metadata:
  name: secret-duplicator-cert-gen
  namespace : {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    k8s-app: secret-duplicator-cert-gen
  name: secret-duplicator-cert-gen
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
      - serviceaccounts
    verbs:
      - list
      - patch
      - create
      - get
      - delete
  - apiGroups:
      - ""
    resources:
      - namespaces
    verbs:
      - list
      - get
  - apiGroups:
      - certificates.k8s.io
    resources:
      - certificatesigningrequests
    verbs:
      - create
      - list
      - get
      - delete
  - apiGroups:
      - certificates.k8s.io
    resources:
      - certificatesigningrequests/approval
    verbs:
      - update
  - apiGroups:
      - certificates.k8s.io
    resources:
      - signers
    resourceNames:
      - kubernetes.io/kubelet-serving
    verbs:
      - approve
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: secret-duplicator-cert-gen
  labels:
    {{- include "secret-duplicator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: secret-duplicator-cert-gen
subjects:
  - kind: ServiceAccount
    name: secret-duplicator-cert-gen
    namespace : {{ .Release.Namespace }}
