apiVersion: v1
kind: ServiceAccount
metadata:
  name: secret-duplicator
  namespace : {{ .Release.Namespace }}
  labels:
    {{- include "secret-duplicator.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    k8s-app: secret-duplicator
    {{- include "secret-duplicator.labels" . | nindent 4 }}
  name: secret-duplicator
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - list
      - patch
      - create
      - get
      - delete
      - update
  - apiGroups:
      - ""
    resources:
      - namespaces
    verbs:
      - list
      - get
  - apiGroups:
      - "certificates.k8s.io/v1"
    resources:
      - certificatesigningrequests
    verbs:
      - create
      - list
      - get
  - apiGroups:
      - "certificates.k8s.io/v1"
    resources:
      - certificatesigningrequests/approval
    verbs:
      - update
  - apiGroups:
      - certificates.k8s.io
    resources:
      - signers
    resourceNames:
      - kubernetes.io/kubelet-serving
    verbs:
      - approve
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: secret-duplicator
  labels:
    {{- include "secret-duplicator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: secret-duplicator
subjects:
  - kind: ServiceAccount
    name: secret-duplicator
    namespace : {{ .Release.Namespace }}
